pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                   sshagent(['tomcat-dev']) {
           sh 'ssh -o StrictHostKeyChecking=no target/*.war ec2-user@3.83.104.170:/home/ec2-user/opt/apache-tomcat-8.5.34/webapps/'

                 }

            }
        }
    }
}
